FROM node:18.18.0-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm i

# Copy the rest of your application code
COPY . .

# Expose port and run the application
EXPOSE 3000
CMD ["npm", "run", "dev"]
